name: deployToVercel

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: yarn install
        run: yarn install

      - name: run tests
        run: yarn lint

      - name: build
        run: yarn build

      - name: deploy
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ebe4G0eV63h12bhOeF8OWTaz
          vercel-org-id: th0Xo7Aa311vlUkEzA89xTTQ
          vercel-project-id: prj_Xttg0XOT8wc7RWwAX8g6tUV2VUxe
          github-token: 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
