name: deploy to vercel

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: yarn install
        run: yarn install

      - name: run tests
        run: yarn lint

      - name: build
        run: yarn build

      - name: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ actionsKey.VERCEL_TOKEN }}
          vercel-org-id: ${{ actionsKey.VERCEL_ORG_ID }}
          vercel-project-id: ${{ actionsKey.VERCEL_PROJECT_ID }}
          github-token: ${{ actionsKey.ACCESS_TOKEN_GITHUB }}
